---
name: lint_python
on: [pull_request, push]
jobs:
  pyright:
    name: Check types with pyright
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-platform: ["Linux"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    env:
      PYRIGHT_VERSION: 1.1.235
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -e .[nomujoco]
      - uses: jakebailey/pyright-action@v1
        with:
          version: ${{ env.PYRIGHT_VERSION }}
          python-platform: ${{ matrix.python-platform }}
          python-version: ${{ matrix.python-version }}
          no-comments: ${{ matrix.python-version != '3.9' || matrix.python-platform != 'Linux' }}  # Having each job create the same comment is too noisy.
